<?php
declare(strict_types=1);
require_once __DIR__.'/mailer.php';
$view=(string)($_GET['view']??'dashboard');
if($view==='logout'){admin_logout();redirect('admin.php?view=login');}
if($view==='login'){
 if(is_admin())redirect('admin.php');$err='';if(($_SERVER['REQUEST_METHOD']??'')==='POST'){require_csrf();if(admin_login((string)($_POST['username']??''),(string)($_POST['password']??'')))redirect('admin.php');$err='Anmeldung fehlgeschlagen.';}
 ?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login</title><link rel="stylesheet" href="assets/style.css"></head><body class="login-body"><div class="login-card"><div class="brand"><div class="brand-mark">FH</div><div><strong>Web-Admin</strong><span>Friedrich Hamel GmbH</span></div></div><?php if($err):?><div class="alert error"><?=h($err)?></div><?php endif?><form method="post" class="form-grid"><?=csrf_field()?><label class="full"><span>Benutzername</span><input name="username" required autofocus></label><label class="full"><span>Passwort</span><input type="password" name="password" required></label><button class="btn btn-primary full">Anmelden</button></form></div></body></html><?php exit;
}
require_admin();$admin=current_admin();
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 require_csrf();$a=(string)($_POST['action']??'');
 try{
  if($a==='approve'){ $id=(int)$_POST['id'];$days=max(1,min(3650,(int)($_POST['days']??DEFAULT_LICENSE_DAYS)));$max=max(1,min(20,(int)($_POST['max_devices']??DEFAULT_MAX_DEVICES)));$r=approve_application($id,$days,$max);flash('success','Antrag freigegeben. Lizenz wurde erzeugt, aber NICHT automatisch per E-Mail versendet.');redirect('admin.php?view=license&id='.$r['license_id']); }
  if($a==='reject'){ $id=(int)$_POST['id'];$reason=trim((string)($_POST['reason']??''));db()->prepare("UPDATE aufmass_lizenz_antraege SET status='abgelehnt',ablehnungsgrund=?,bearbeitet_von=?,bearbeitet_am=NOW() WHERE id=? AND status='offen'")->execute([$reason?:null,(int)$_SESSION['admin_id'],$id]);audit('antrag_abgelehnt','antrag',$id,['grund'=>$reason]);flash('success','Antrag abgelehnt. Keine Lizenz und keine Lizenzmail wurden erzeugt.');redirect('admin.php?view=requests'); }
  if($a==='send_license'){send_license_mail((int)$_POST['license_id']);flash('success','Lizenzmail wurde jetzt manuell versendet.');redirect('admin.php?view=license&id='.(int)$_POST['license_id']);}
  if($a==='toggle_user'){db()->prepare('UPDATE aufmass_cloud_benutzer SET aktiv=? WHERE id=?')->execute([(int)$_POST['aktiv'],(int)$_POST['id']]);audit('benutzer_status','benutzer',(int)$_POST['id']);flash('success','Benutzerstatus geändert.');redirect('admin.php?view=user&id='.(int)$_POST['id']);}
  if($a==='save_user'){$id=(int)$_POST['id'];$email=normalize_email((string)$_POST['email']);if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Ungültige E-Mail.');db()->prepare('UPDATE aufmass_cloud_benutzer SET name=?,email=?,max_geraete=? WHERE id=?')->execute([trim((string)$_POST['name']),$email,max(1,min(20,(int)$_POST['max_devices'])),$id]);audit('benutzer_bearbeitet','benutzer',$id);flash('success','Benutzer gespeichert.');redirect('admin.php?view=user&id='.$id);}
  if($a==='toggle_license'){db()->prepare('UPDATE aufmass_cloud_lizenzen SET aktiv=? WHERE id=?')->execute([(int)$_POST['aktiv'],(int)$_POST['id']]);audit('lizenz_status','lizenz',(int)$_POST['id']);flash('success','Lizenzstatus geändert.');redirect('admin.php?view=license&id='.(int)$_POST['id']);}
  if($a==='rotate_license'){rotate_license((int)$_POST['id'],true);flash('success','Neuer Lizenz-Key erzeugt. Geräte wurden gesperrt. Noch KEINE Mail versendet.');redirect('admin.php?view=license&id='.(int)$_POST['id']);}
  if($a==='toggle_device'){db()->prepare('UPDATE aufmass_cloud_geraete SET aktiv=? WHERE id=?')->execute([(int)$_POST['aktiv'],(int)$_POST['id']]);audit('geraet_status','geraet',(int)$_POST['id']);flash('success','Gerätestatus geändert.');redirect('admin.php?view=license&id='.(int)$_POST['license_id']);}
  if($a==='delete_device'){db()->prepare('DELETE FROM aufmass_cloud_geraete WHERE id=?')->execute([(int)$_POST['id']]);audit('geraet_entfernt','geraet',(int)$_POST['id']);flash('success','Gerät entfernt; Geräteplatz ist frei.');redirect('admin.php?view=license&id='.(int)$_POST['license_id']);}
  if($a==='create_user'){ $r=create_user_with_license(trim((string)$_POST['name']),(string)$_POST['email'],max(1,(int)$_POST['days']),max(1,(int)$_POST['max_devices']));flash('success','Nutzer + Lizenz angelegt. Noch KEINE Lizenzmail versendet.');redirect('admin.php?view=license&id='.$r['license_id']); }
  if($a==='custom_mail'){send_custom_mail((string)$_POST['to'],trim((string)$_POST['subject']),trim((string)$_POST['message']),($_POST['user_id']??'')!==''?(int)$_POST['user_id']:null);flash('success','E-Mail versendet.');redirect('admin.php?view=mail');}
  if($a==='test_mail'){smtp_send(normalize_email((string)$_POST['to']),'SMTP-Test – Friedrich Hamel Aufmaß','<p>Der SMTP-Versand funktioniert.</p>');mail_log((string)$_POST['to'],'SMTP-Test – Friedrich Hamel Aufmaß',true,'test');flash('success','Testmail versendet.');redirect('admin.php?view=mail');}
  if($a==='add_category'){$n=trim((string)$_POST['name']);if($n==='')throw new RuntimeException('Name fehlt.');ensure_category_room_template($n);flash('success','Kategorie und gleichnamige Raum-Vorlage angelegt.');redirect('admin.php?view=catalog');}
  if($a==='add_material'){$m=trim((string)$_POST['material']);$c=trim((string)$_POST['category']);if($m===''||$c==='')throw new RuntimeException('Material/Kategorie fehlt.');ensure_category_room_template($c);db()->prepare('INSERT INTO material_katalog(material,kategorie) VALUES(?,?)')->execute([$m,$c]);flash('success','Material angelegt.');redirect('admin.php?view=catalog');}
  if($a==='add_room_material'){$rid=(int)$_POST['room_id'];$m=trim((string)$_POST['material']);db()->prepare('INSERT IGNORE INTO globale_raum_inhalte(vorlage_id,material) VALUES(?,?)')->execute([$rid,$m]);flash('success','Material dem Raum-Master zugeordnet.');redirect('admin.php?view=catalog&room='.$rid);}
 }catch(Throwable $e){flash('error',$e->getMessage());redirect('admin.php?view='.$view);}
}
$flashes=take_flashes();
function nav(string $v,string $label,string $icon='•'):string{global $view;return '<a class="nav-item '.($view===$v?'active':'').'" href="admin.php?view='.h($v).'"><span>'.$icon.'</span>'.h($label).'</a>';}
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aufmaß Admin</title><link rel="stylesheet" href="assets/style.css"></head><body class="admin-body"><aside class="sidebar"><div class="sidebar-brand"><div class="brand"><div class="brand-mark">FH</div><div><strong>Aufmaß Admin</strong><span>Cloud V8</span></div></div></div><nav><?=nav('dashboard','Dashboard','⌂')?><?=nav('requests','Lizenzanträge','✓')?><?=nav('users','Nutzer & Lizenzen','👤')?><?=nav('projects','Cloud-Projekte','☁')?><?=nav('catalog','Katalog & Raum-Master','▦')?><?=nav('mail','E-Mail','✉')?><?=nav('audit','Protokoll','≡')?></nav><div class="sidebar-bottom"><a class="nav-item" href="admin.php?view=logout"><span>↪</span>Abmelden</a></div></aside><main class="admin-main"><header class="admin-header"><div><small>Friedrich Hamel GmbH</small><h1><?=h(ucfirst($view))?></h1></div><div class="status-chip">● <?=h($admin['name']??'Admin')?></div></header><div class="admin-content"><?php foreach($flashes as $f):?><div class="alert <?=h($f['type'])?>"><?=h($f['message'])?></div><?php endforeach;?>
<?php if($view==='dashboard'):$s=['Anträge'=>"SELECT COUNT(*) FROM aufmass_lizenz_antraege WHERE status='offen'",'Nutzer'=>'SELECT COUNT(*) FROM aufmass_cloud_benutzer','Aktive Lizenzen'=>'SELECT COUNT(*) FROM aufmass_cloud_lizenzen WHERE aktiv=1','Aktive Geräte'=>'SELECT COUNT(*) FROM aufmass_cloud_geraete WHERE aktiv=1','Projekte'=>'SELECT COUNT(*) FROM aufmass_cloud_projekte WHERE deleted_at IS NULL'];?><div class="stats"><?php foreach($s as $k=>$sql):?><div class="stat"><span><?=h($k)?></span><strong><?=(int)db()->query($sql)->fetchColumn()?></strong><small>aktuell</small></div><?php endforeach;?></div><div class="panel"><h2>Systemstatus</h2><p>API: <b><?=h(APP_URL)?>/lizenz_api.php</b></p><p>Lizenzversand: <b>manuell nach Freigabe</b>. Eine Freigabe verschickt niemals automatisch einen Key.</p></div>
<?php elseif($view==='requests'):$rows=db()->query("SELECT * FROM aufmass_lizenz_antraege ORDER BY FIELD(status,'offen','freigegeben','abgelehnt'),erstellt_am DESC LIMIT 300")->fetchAll();?><div class="panel"><h2>Lizenzanträge</h2><div class="table-wrap"><table><tr><th>Status</th><th>Name</th><th>E-Mail</th><th>Geräte</th><th>Datum</th><th>Aktion</th></tr><?php foreach($rows as $r):?><tr><td><span class="badge <?=h($r['status'])?>"><?=h($r['status'])?></span></td><td><b><?=h($r['name'])?></b><br><small><?=h($r['firma'])?></small></td><td><?=h($r['email'])?></td><td><?=(int)$r['gewuenschte_geraete']?></td><td><?=h(format_dt($r['erstellt_am']))?></td><td><?php if($r['status']==='offen'):?><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="approve"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="days" value="<?=DEFAULT_LICENSE_DAYS?>"><input type="hidden" name="max_devices" value="<?=$r['gewuenschte_geraete']?>"><button class="btn btn-primary btn-sm">Freigeben</button></form> <form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="reject"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="reason" value="Administrativ abgelehnt"><button class="btn btn-danger btn-sm">Ablehnen</button></form><?php endif?></td></tr><?php endforeach?></table></div></div>
<?php elseif($view==='users'):$rows=db()->query("SELECT b.*,COUNT(DISTINCT l.id) lizenzen,COUNT(DISTINCT g.id) geraete FROM aufmass_cloud_benutzer b LEFT JOIN aufmass_cloud_lizenzen l ON l.benutzer_id=b.id LEFT JOIN aufmass_cloud_geraete g ON g.benutzer_id=b.id AND g.aktiv=1 GROUP BY b.id ORDER BY b.id DESC")->fetchAll();?><div class="panel"><div class="panel-head"><h2>Nutzer</h2></div><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="create_user"><label><span>Name</span><input name="name" required></label><label><span>E-Mail</span><input type="email" name="email" required></label><label><span>Laufzeit Tage</span><input type="number" name="days" value="<?=DEFAULT_LICENSE_DAYS?>"></label><label><span>Max. Geräte</span><input type="number" name="max_devices" value="<?=DEFAULT_MAX_DEVICES?>"></label><button class="btn btn-primary full">+ Nutzer + Lizenz (ohne Mail)</button></form><hr><div class="table-wrap"><table><tr><th>Nutzer</th><th>Status</th><th>Geräte</th><th>Lizenzen</th></tr><?php foreach($rows as $r):?><tr><td><a href="admin.php?view=user&id=<?=$r['id']?>"><b><?=h($r['name'])?></b></a><br><small><?=h($r['email'])?></small></td><td><span class="badge <?=$r['aktiv']?'active':'blocked'?>"><?=$r['aktiv']?'aktiv':'gesperrt'?></span></td><td><?=$r['geraete']?> / <?=$r['max_geraete']?></td><td><?=$r['lizenzen']?></td></tr><?php endforeach?></table></div></div>
<?php elseif($view==='user'):$id=(int)($_GET['id']??0);$q=db()->prepare('SELECT * FROM aufmass_cloud_benutzer WHERE id=?');$q->execute([$id]);$u=$q->fetch();if(!$u):?><div class="alert error">Nutzer nicht gefunden.</div><?php else:$l=db()->prepare('SELECT * FROM aufmass_cloud_lizenzen WHERE benutzer_id=? ORDER BY id DESC');$l->execute([$id]);?><div class="detail-grid"><div class="panel"><h2>Nutzer bearbeiten</h2><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="save_user"><input type="hidden" name="id" value="<?=$id?>"><label><span>Name</span><input name="name" value="<?=h($u['name'])?>"></label><label><span>E-Mail</span><input name="email" value="<?=h($u['email'])?>"></label><label><span>Max. Geräte</span><input type="number" name="max_devices" value="<?=$u['max_geraete']?>"></label><button class="btn btn-primary">Speichern</button></form><form method="post" class="top-gap"><?=csrf_field()?><input type="hidden" name="action" value="toggle_user"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="aktiv" value="<?=$u['aktiv']?0:1?>"><button class="btn <?=$u['aktiv']?'btn-danger':''?>"><?=$u['aktiv']?'Nutzer sperren':'Nutzer aktivieren'?></button></form></div><div class="panel"><h2>Lizenzen</h2><?php foreach($l->fetchAll() as $x):?><p><a href="admin.php?view=license&id=<?=$x['id']?>">Lizenz #<?=$x['id']?></a> · <?=h(format_dt($x['gueltig_bis']))?> · <?=$x['aktiv']?'aktiv':'gesperrt'?></p><?php endforeach?></div></div><?php endif;
?><?php elseif($view==='license'):$id=(int)($_GET['id']??0);$q=db()->prepare('SELECT l.*,b.name,b.email,b.max_geraete FROM aufmass_cloud_lizenzen l JOIN aufmass_cloud_benutzer b ON b.id=l.benutzer_id WHERE l.id=?');$q->execute([$id]);$l=$q->fetch();if(!$l):?><div class="alert error">Lizenz nicht gefunden.</div><?php else:$g=db()->prepare('SELECT * FROM aufmass_cloud_geraete WHERE lizenz_id=? ORDER BY id DESC');$g->execute([$id]);?><div class="panel"><h2>Lizenz #<?=$id?> – <?=h($l['name'])?></h2><p><b>Gültig bis:</b> <?=h(format_dt($l['gueltig_bis']))?> · <b>Status:</b> <?=$l['aktiv']?'aktiv':'gesperrt'?></p><?php try{$key=license_key_for_id($id);?><p><span class="license-key"><?=h($key)?></span></p><?php }catch(Throwable $e):?><div class="alert warn"><?=h($e->getMessage())?></div><?php endtry?><div class="alert warn"><b>Wichtig:</b> Der Key wird erst durch den folgenden separaten Knopf per E-Mail versendet.</div><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="send_license"><input type="hidden" name="license_id" value="<?=$id?>"><button class="btn btn-primary">Lizenz jetzt per E-Mail senden</button></form> <form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="rotate_license"><input type="hidden" name="id" value="<?=$id?>"><button class="btn">Neuen Key erzeugen</button></form> <form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="toggle_license"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="aktiv" value="<?=$l['aktiv']?0:1?>"><button class="btn <?=$l['aktiv']?'btn-danger':''?>"><?=$l['aktiv']?'Sperren':'Aktivieren'?></button></form></div><div class="panel"><h2>Geräte</h2><div class="table-wrap"><table><tr><th>Gerät</th><th>Status</th><th>Zuletzt online</th><th>Aktion</th></tr><?php foreach($g->fetchAll() as $x):?><tr><td><b><?=h($x['geraet_name'])?></b><br><small><?=h(substr($x['geraet_fingerprint'],0,18))?>…</small></td><td><?=$x['aktiv']?'aktiv':'gesperrt'?></td><td><?=h(format_dt($x['zuletzt_online']))?></td><td><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="toggle_device"><input type="hidden" name="id" value="<?=$x['id']?>"><input type="hidden" name="license_id" value="<?=$id?>"><input type="hidden" name="aktiv" value="<?=$x['aktiv']?0:1?>"><button class="btn btn-sm"><?=$x['aktiv']?'Sperren':'Aktivieren'?></button></form> <form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="action" value="delete_device"><input type="hidden" name="id" value="<?=$x['id']?>"><input type="hidden" name="license_id" value="<?=$id?>"><button class="btn btn-danger btn-sm">Entfernen</button></form></td></tr><?php endforeach?></table></div></div><?php endif;
?><?php elseif($view==='projects'):$rows=db()->query("SELECT p.*,b.name benutzer FROM aufmass_cloud_projekte p JOIN aufmass_cloud_benutzer b ON b.id=p.benutzer_id ORDER BY p.server_geaendert_am DESC LIMIT 500")->fetchAll();?><div class="panel"><h2>Cloud-Projekte</h2><div class="table-wrap"><table><tr><th>Projekt</th><th>Nutzer</th><th>Status</th><th>Geändert</th></tr><?php foreach($rows as $r):?><tr><td><b><?=h($r['name'])?></b><br><small><?=h($r['projekt_uuid'])?></small></td><td><?=h($r['benutzer'])?></td><td><?=$r['deleted_at']?'gelöscht':'aktiv'?></td><td><?=h(format_dt($r['server_geaendert_am']))?></td></tr><?php endforeach?></table></div></div>
<?php elseif($view==='catalog'):$cats=db()->query('SELECT * FROM katalog_kategorien ORDER BY name')->fetchAll();$mats=db()->query('SELECT * FROM material_katalog ORDER BY kategorie,material')->fetchAll();$rooms=db()->query('SELECT * FROM globale_raum_vorlagen ORDER BY name')->fetchAll();$roomId=(int)($_GET['room']??0);?><div class="detail-grid"><div><div class="panel"><h2>Kategorien</h2><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="add_category"><label class="full"><span>Neue Kategorie</span><input name="name" placeholder="z. B. Beleuchtung" required></label><button class="btn btn-primary full">Kategorie + Raum-Vorlage anlegen</button></form><?php foreach($cats as $c):?><p><?=h($c['name'])?></p><?php endforeach?></div><div class="panel"><h2>Material</h2><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="add_material"><label><span>Material</span><input name="material" required></label><label><span>Kategorie</span><input name="category" required></label><button class="btn btn-primary full">Material anlegen</button></form><hr><?php foreach($mats as $m):?><p><b><?=h($m['material'])?></b> <small>· <?=h($m['kategorie'])?></small></p><?php endforeach?></div></div><div class="panel"><h2>Raum-Master</h2><?php foreach($rooms as $r):?><p><a href="admin.php?view=catalog&room=<?=$r['id']?>"><?=h($r['name'])?></a></p><?php endforeach?><?php if($roomId):$q=db()->prepare('SELECT name FROM globale_raum_vorlagen WHERE id=?');$q->execute([$roomId]);$rn=$q->fetchColumn();$q=db()->prepare('SELECT material FROM globale_raum_inhalte WHERE vorlage_id=? ORDER BY id');$q->execute([$roomId]);?><hr><h3><?=h((string)$rn)?></h3><?php foreach($q->fetchAll(PDO::FETCH_COLUMN) as $x):?><p><?=h($x)?></p><?php endforeach?><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="add_room_material"><input type="hidden" name="room_id" value="<?=$roomId?>"><label class="full"><span>Material zum Master hinzufügen</span><input name="material" required></label><button class="btn btn-primary full">Hinzufügen</button></form><?php endif?></div></div>
<?php elseif($view==='mail'):$logs=db()->query('SELECT * FROM aufmass_mail_log ORDER BY id DESC LIMIT 100')->fetchAll();?><div class="detail-grid"><div class="panel"><h2>Individuelle E-Mail</h2><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="custom_mail"><label class="full"><span>Empfänger</span><input type="email" name="to" required></label><label class="full"><span>Betreff</span><input name="subject" required></label><label class="full"><span>Nachricht</span><textarea name="message" rows="8" required></textarea></label><button class="btn btn-primary full">E-Mail senden</button></form><hr><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="test_mail"><label class="full"><span>SMTP-Test an</span><input type="email" name="to" required></label><button class="btn full">SMTP testen</button></form></div><div class="panel"><h2>Mailprotokoll</h2><?php foreach($logs as $x):?><p><b><?=h($x['empfaenger'])?></b><br><small><?=h($x['betreff'])?> · <?=$x['erfolgreich']?'OK':'FEHLER'?> · <?=h(format_dt($x['erstellt_am']))?></small></p><?php endforeach?></div></div>
<?php elseif($view==='audit'):$rows=db()->query('SELECT a.*,ad.benutzername FROM aufmass_audit_log a LEFT JOIN aufmass_admins ad ON ad.id=a.admin_id ORDER BY a.id DESC LIMIT 300')->fetchAll();?><div class="panel"><h2>Audit-Protokoll</h2><div class="table-wrap"><table><tr><th>Zeit</th><th>Admin</th><th>Aktion</th><th>Objekt</th></tr><?php foreach($rows as $r):?><tr><td><?=h(format_dt($r['erstellt_am']))?></td><td><?=h($r['benutzername']??'System')?></td><td><?=h($r['aktion'])?></td><td><?=h($r['entity_typ'])?> #<?=h((string)$r['entity_id'])?></td></tr><?php endforeach?></table></div></div><?php endif?></div></main></body></html>
